config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products,   only: :index
  resources :line_items, only: :create
  resources :orders,     only: :index

  resources :charges,    only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :calculate_total

  delegate :name, :price, to: :product

  private

  def calculate_total
    self.total = quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :line_items

  def total
    line_items.sum(:total)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :orders

  def order
    orders.last 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_order, only: :create

  def new
    @amount   = params[:amount].to_f
    @order_id = params[:order_id]
  end

  def create
    charge = Stripe::Charge.create(
      amount:      params[:amount],
      description: 'Rails Stripe customer',
      source:      params[:stripeToken],
      currency:    'usd'
    )

    order.update(state: 'completed')

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private

  attr_reader :order

  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_order, only: :create

  def create
    order.line_items << LineItem.new(line_item_params)

    if order.save
      render json: order, status: 200
    else
      render json: { errors: order.errors.full_messages }, status: 422
    end
  end

  private

  attr_reader :order

  def set_order
    @order = current_user.order || current_user.orders.build
  end

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <%= hidden_field_tag :amount,   @amount.to_i * 100 %>
  <%= hidden_field_tag :order_id, @order_id %>

  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @amount%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeAcademy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
  <%= order.id %>:
  <%= form_tag new_charge_path, method: :get do %>
    <%= hidden_field_tag :order_id, order.id %>
    <%= label_tag :amount,'Amount' %>
    <%= text_field_tag :amount, order.total.to_f %>
    <%= submit_tag 'Pay' %>
  <% end %>
  <br/>
<% end %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <%= product.name %>:
  <%= product.price %>
  <%= form_for LineItem.new, remote: true do |form| %>
    <%= form.hidden_field :product_id, value: product.id %>
    <%= form.number_field :quantity,   value: 1 %>
    <%= form.submit %>
  <% end %>
  <br/>
<% end %>